"""empty message

Revision ID: d2c09af80c37
Revises: 0c7adfd7d311
Create Date: 2019-07-25 20:30:34.981166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c09af80c37'
down_revision = '0c7adfd7d311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_actor_id'), 'actor', ['id'], unique=False)
    op.create_index(op.f('ix_movie_id'), 'movie', ['id'], unique=False)
    op.create_index(op.f('ix_movie_to_actor_actor_id'), 'movie_to_actor', ['actor_id'], unique=False)
    op.create_index(op.f('ix_movie_to_actor_movie_id'), 'movie_to_actor', ['movie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_to_actor_movie_id'), table_name='movie_to_actor')
    op.drop_index(op.f('ix_movie_to_actor_actor_id'), table_name='movie_to_actor')
    op.drop_index(op.f('ix_movie_id'), table_name='movie')
    op.drop_index(op.f('ix_actor_id'), table_name='actor')
    # ### end Alembic commands ###
